import SwiftUI
import PhotosUI

struct ContentView: View {
    @State private var artwork: PhotosPickerItem?
    @State private var proofFiles: [PhotosPickerItem] = []
    @State private var artworkImage: UIImage?
    @State private var statusText: String = ""
    @State private var isVerifying: Bool = false
    
    var body: some View {
        ScrollView {
            VStack(spacing: 40) {
                
                // HEADER
                header
                
                // HERO
                heroSection
                
                // ABOUT
                aboutSection
                
                // UPLOAD
                uploadSection
                
                // PROCESS
                processSection
                
                // PRICING
                pricingSection
                
                // CONTACT
                contactSection
                
                footer
            }
            .padding()
        }
    }
    
    // HEADER
    var header: some View {
        HStack {
            Text("PM")
                .font(.largeTitle.bold())
            Spacer()
            HStack(spacing: 20) {
                Text("About")
                Text("Process")
                Text("Pricing")
                Text("Contact")
            }
            .font(.headline)
        }
    }
    
    // HERO
    var heroSection: some View {
        VStack(spacing: 10) {
            Text("Certify Your Art as Human-Made")
                .font(.largeTitle.bold())
                .multilineTextAlignment(.center)
            
            Text("Protect your work. Build trust. Stand out in the age of AI.")
                .font(.subheadline)
                .multilineTextAlignment(.center)
            
            Button("Get Certified") {}
                .padding()
                .frame(maxWidth: .infinity)
                .background(Color.blue)
                .foregroundColor(.white)
                .cornerRadius(10)
        }
    }
    
    // ABOUT
    var aboutSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("About Us")
                .font(.title.bold())
            
            Text("""
            PMAC (PeopleMade Art Certification) verifies that artwork was created by real human artists, not generated by AI. Using process evidence, forensic analysis, and metadata checks, we provide trusted certificates for collectors, galleries, and artists.
            """)
        }
    }
    
    // UPLOAD
    var uploadSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Upload Artwork for Certification")
                .font(.title.bold())
            
            Text("Select your artwork and any optional proof files.")
            
            VStack(spacing: 15) {
                
                // Artwork picker
                PhotosPicker(selection: $artwork, matching: .images) {
                    Label("Select Artwork File", systemImage: "photo")
                }
                
                // Proof files picker
                PhotosPicker(selection: $proofFiles, matching: .any, photoLibrary: .shared()) {
                    Label("Upload Optional Proof Files", systemImage: "folder")
                }
                
                // Preview
                if let img = artworkImage {
                    Image(uiImage: img)
                        .resizable()
                        .scaledToFit()
                        .frame(height: 200)
                        .cornerRadius(10)
                }
                
                // Button
                Button(action: startVerification) {
                    Text("Submit for Verification")
                        .padding()
                        .frame(maxWidth: .infinity)
                        .background(Color.blue)
                        .foregroundColor(.white)
                        .cornerRadius(10)
                }
                
                // Status output
                ScrollView {
                    Text(statusText)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding()
                }
                .frame(height: 200)
                .background(Color.gray.opacity(0.1))
                .cornerRadius(10)
                
            }
            .task(id: artwork) {
                if let data = try? await artwork?.loadTransferable(type: Data.self),
                   let uiImage = UIImage(data: data) {
                    artworkImage = uiImage
                }
            }
        }
    }
    
    // PROCESS
    var processSection: some View {
        VStack(alignment: .leading, spacing: 20) {
            Text("How Certification Works")
                .font(.title.bold())
            
            VStack(alignment: .leading, spacing: 25) {
                processStep(num: 1, title: "Upload Your Artwork", desc: "Submit the finished piece and optional time-lapse, PSD files, or sketches.")
                processStep(num: 2, title: "Verification & AI Screening", desc: "We analyze metadata, layer data, and run AI-detection tools.")
                processStep(num: 3, title: "Human Review", desc: "Our reviewers check creation evidence and confirm authenticity.")
                processStep(num: 4, title: "Receive Your Certificate", desc: "You get a tamper-proof certificate with a unique ID and verification link.")
            }
        }
    }
    
    func processStep(num: Int, title: String, desc: String) -> some View {
        VStack(alignment: .leading) {
            Text("\(num). \(title)")
                .font(.headline)
            Text(desc)
                .font(.subheadline)
        }
    }
    
    // PRICING
    var pricingSection: some View {
        VStack(alignment: .leading, spacing: 20) {
            Text("Pricing")
                .font(.title.bold())
            
            VStack(spacing: 20) {
                priceCard(name: "Single Certification", price: 10, features: [
                    "1 artwork",
                    "Metadata & forensic analysis",
                    "Human review",
                    "Certificate with ID"
                ])
                
                priceCard(name: "Artist Bundle", price: 50, highlight: true, features: [
                    "10 certifications",
                    "Priority review",
                    "Artist portfolio page",
                    "Certificate verification link"
                ])
                
                priceCard(name: "Gallery Plan", price: 199, features: [
                    "50 certifications",
                    "Dedicated reviewer",
                    "Bulk submission",
                    "Custom badges for art sales"
                ])
            }
        }
    }
    
    func priceCard(name: String, price: Int, highlight: Bool = false, features: [String]) -> some View {
        VStack(spacing: 10) {
            Text(name).font(.headline)
            Text("$\(price)").font(.largeTitle.bold())
            ForEach(features, id: \.self) { feature in
                Text("• \(feature)")
            }
            Button("Choose") {}
                .padding()
                .frame(maxWidth: .infinity)
                .background(highlight ? Color.blue : Color.gray.opacity(0.3))
                .foregroundColor(highlight ? .white : .black)
                .cornerRadius(10)
        }
        .padding()
        .background(Color.white)
        .cornerRadius(15)
        .shadow(radius: 3)
    }
    
    // CONTACT
    var contactSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("Contact Us")
                .font(.title.bold())
            
            Text("Email: support@pmac-certify.com")
            Text("Instagram: @pmac.verify")
            Text("Business Hours: Mon–Fri, 9 AM–5 PM")
        }
    }
    
    // FOOTER
    var footer: some View {
        Text("© 2025 PMAC — PeopleMade Art Certification")
            .font(.footnote)
            .foregroundColor(.gray)
            .padding(.top, 30)
    }
    
    // VERIFICATION PROCESS
    func startVerification() {
        statusText = ""
        
        guard artwork != nil else {
            statusText = "❌ Please upload your artwork file."
            return
        }
        
        isVerifying = true
        
        let steps = [
            "Uploading artwork...",
            "Checking metadata...",
            "Analyzing for AI patterns...",
            "Processing optional proof files...",
            "Human reviewer validation...",
            "Finalizing certificate..."
        ]
        
        var delay: Double = 0
        
        for step in steps {
            DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
                statusText += step + "\n"
            }
            delay += 0.8
        }
        
        DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
            let certID = "PMAC-" + UUID().uuidString.prefix(8)
            statusText += "\n✅ Verification Complete!\nYour Certificate ID:\n\(certID)"
        }
    }
}

# PREVIEW
# (Optional, only for Xcode canvas)
struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}